[general]
email = "mpearson@nalresearch.com"

[github]
repo = "mat-gpt/matgpt-v7-1"
branch = "main"
deploy_key = """
-----BEGIN OPENSSH PRIVATE KEY-----
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz3H1vnQh6/xBgNBfDtIk3T4JQDMnyaZeIdkl4UmZmq/Hj7CsbFGsteAWTroQFh5v+ZO2pvh7Du0AFiNu+ZGmbxOukA3yyZ0HN/CLQ6W3RbCqpHxK/f59+lkbHI/aiHSBHxy2GeoxGl/wEQpBHHojAD2UsHP/SiQgoneDIKXLqnf0CiEfGmnnWkTAtGj5dKnWyUDIG7/8rT2ch0Ey9OxPdKaYgu3ZnVja5mT6ajhk6WzjGEu67uQEN47rXqOqONuqc1nLt2lfDTJ0P0rdx+b4XzN7U6zwMBzJCGXIhTQd3XT6HT25gK4Xi13r8rymWf5O2P+qN2SjnniimgXS11fnpUCr+Z6Gf3/Skpwjbzn/O0PNLcu3GilYcIDdZQ71a/0C4u2hwt5sCmdcZEAV8VmeXiZuWzRfj6Kp4+0Hzgy4We3BLDnJGswIf2YlrOMgxqJy6fXomwgsPRm8/VkvJYJXEu78PNwOLDpdxigMG1rIvbO/ZpU5TlaL7/xuhhK8majdOYnmcCPJLwKBMhNEGO5wVkTkNeYrhR9z2kn46XLM+osHdPC1M3UyREihfiysC+7YkzRxb4QLITZIPeEoUTk9Ck4ifrjgPCQLrqMQI/jm8ToRddBgU6Rnqp3ExXuksDKk1ah27KvAm7ok6UX8ZW/Kwcj2SKoEoPreG/L3aY9Ezow== matgpt-deploy
-----END OPENSSH PRIVATE KEY-----
"""

DATABASE_PATH = "matgpt.db"